spring:
  redis:
    host: 
    port: 
    password: 
    timeout: 15000
  kafka:
    bootstrap-servers: 
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
    producer:
      retries: 10
      acks: -1
      properties:
        retry:
          backoff:
            ms:
              200
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8888